import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/app/_components/layout/header";
import { Providers } from "@/components/providers";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className}  antialiased dark max-w-[100vw] overflow-x-hidden`}
      >
        <Providers>
          <Header />
          <div className="mx-auto min-h-[calc(100vh-6rem)] max-w-screen-2xl border-x border-dashed border-border p-4">
            {children}
          </div>
        </Providers>

        <Toaster />
      </body>
    </html>
  );
}
